### ISSUE TITLE
Unhandled Exception when invoking FTToolsLauncher

### ISSUE THREAD

**Issue by S-278** [MicroFocus/ADM-FT-ToolsLauncher#99]
**Tool**
FTToolsLauncher

**Describe the bug**
When I simply invoke the FTToolsLauncher.exe from the command prompt, I get an Unhandled Exception (see screenshot).

**To Reproduce**

1. Download `FTToolsLauncher_net48.exe` from the latest release on this repo
2. Invoke `FTToolsLauncher_net48.exe` from Windows administrator command prompt (the same behavior occurs when I supply a paramfile)

**Expected behavior**
The app launches and shows a "help" or "usage" text.

**Screenshots**
![Screenshot 2024-06-14 141336](https://github.com/MicroFocus/ADM-FT-ToolsLauncher/assets/82274989/40537641-bf27-4ea8-bcbc-d3e2637399b1)

**OS and testing tools (please complete the following information):**
- OS: Windows Server 2022 Standard version 21H2
- UFT One version: 2022.0.0.1004

**Additional context**
I have verified that .NET 4.8 is installed (`C:\Windows\Microsoft.NET\Framework\v4.0.30319` exists)

I have also verified that the exe file hash matches the hash given in the release.

**Comment by dorin7bogdan** [comment]
Hello,

The specific System.AccessViolationException indicates an attempt to read or write to protected memory, which suggests a memory corruption issue.

Here are some potential causes and solutions:

**1. Corrupted .NET Framework Installation:** Even though .NET 4.8 is installed, the installation might be corrupted.
**Solution:** Repair the .NET Framework installation. You can do this via the Control Panel by finding .NET Framework and selecting the repair option, or you can use the .NET Framework Repair Tool from Microsoft.

**2. Third-Party Interference:** Certain third-party software, especially those that interact with system memory or provide security features, can cause memory access issues.
**Solution:** Temporarily disable any third-party antivirus or security software and see if the problem persists. If it does, try running your application in a clean boot state to see if any background services or applications are causing the issue.

**3. Faulty Hardware:** Memory corruption can sometimes be due to faulty hardware, particularly RAM.
**Solution:** Run memory diagnostic tools like the Windows Memory Diagnostic to check for any issues with your RAM.

----------------------------------------------------------------

Here are steps to repair .NET Framework installation:
- Open Control Panel.
- Navigate to Programs and Features.
- Find .NET Framework 4.8 in the list of installed programs.
- Select it and choose "Repair."
Alternatively, download and run the [.NET Framework Repair Tool](https://www.microsoft.com/en-us/download/details.aspx?id=30135).

You can also run the Windows Memory Diagnostic by following these steps:
- Press **Win + R** to open the Run dialog.
- Type **mdsched.exe** and press Enter.
- Choose whether to restart immediately or check for problems the next time you start your computer.

**Comment by S-278** [comment]
Hello,

Thank you very much for your reply! I tested some of this and eventually found out the issue was due to corrupted folder permissions in Windows. After moving the executable to a different folder, it runs normally.
